server:
  port: 8080

spring:
  application:
    name: MultiLevelCache
  
  # Redis 配置
  redis:
    host: 8.129.17.242
    port: 6379
    password: 1234
    database: 0
    timeout: 2000ms
    lettuce:
      pool:
        max-active: 8
        max-wait: -1ms
        max-idle: 8
        min-idle: 0
  
  # MySQL 數據庫配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/multilevel_cache?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true&autoReconnect=true&failOverReadOnly=false
    username: root
    password: scfmp845
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      connection-test-query: SELECT 1
    
  # MyBatis Plus 配置
  mybatis-plus:
    configuration:
      map-underscore-to-camel-case: true
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    global-config:
      db-config:
        id-type: auto
        logic-delete-field: deleted
        logic-delete-value: 1
        logic-not-delete-value: 0
    mapper-locations: classpath*:/mapper/**/*.xml
    type-aliases-package: com.multilevelcache.entity

# 二級緩存配置
cache:
  # L1 緩存 (Caffeine) - 本地緩存
  caffeine:
    transaction:
      maximum-size: 1000
      expire-after-write: 10s
      expire-after-access: 10s
    blacklist:
      maximum-size: 500
      expire-after-write: 60m
      expire-after-access: 20m
  
  # L2 緩存 (Redis) - 分布式緩存
  redis:
    transaction:
      expire-after-write: 2h
      expire-after-access: 1h
    blacklist:
      expire-after-write: 4h
      expire-after-access: 2h

# 日誌配置
logging:
  level:
    root: info
    com.multilevelcache.cache: debug

# Actuator 配置
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,caches
  endpoint:
    health:
      show-details: when-authorized
      show-components: always
debug: false